name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        path: 'repo' 
    - name: Download pharo
      run: wget -O- https://get.pharo.org/stable+vm | bash
    - name: Build image
      run: ./pharo Pharo.image metacello install filetree://repo BaselineOfMDownToHTMLLambda
    - name: mv bootstrap
      run: mv repo/bootstrap boostrap
    - name: zip
      run: zip -r function.zip *.image *.changes *.sources pharo pharo-vm bootstrap
    - name: ll
      run: ls -al
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: function
        path: function.zip
    
